# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js from package.json
      uses: actions/setup-node@v3
      with:
        node-version-file: 'package.json'
    - run: npm version
    - run: npm ci
    - run: npm test
    - run: npm run semantic-release-dry-run
    - name: Codecov
      uses: codecov/codecov-action@v2.1.0
